In [928]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np
import json

In [929]:
pip install pandas openpyxl

Requirement already satisfied: pandas in /usr/local/lib/python3.12/dist-packages (2.2.2)
Requirement already satisfied: openpyxl in /usr/local/lib/python3.12/dist-packages (3.1.5)
Requirement already satisfied: numpy>=1.26.0 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.12/dist-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /usr/local/lib/python3.12/dist-packages (from pandas) (2025.3)
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.12/dist-packages (from openpyxl) (2.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.12/dist-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [930]:
# Adjust paths accordingly
df1 = pd.read_csv("api_data_aadhar_biometric_0_500000.csv")
df2 = pd.read_csv("api_data_aadhar_biometric_500000_1000000.csv")
df3 = pd.read_csv("api_data_aadhar_biometric_1000000_1500000.csv")
df4 = pd.read_csv("api_data_aadhar_biometric_1500000_1861108.csv")

# Combine all
df = pd.concat([df1, df2, df3, df4], ignore_index=True)

In [931]:
df

,date,state,district,pincode,bio_age_5_17,bio_age_17_
0,01-09-2025,Andaman and Nicobar Islands,Andamans,744103,2,6
1,01-09-2025,Andaman and Nicobar Islands,North And Middle Andaman,744205,6,4
2,01-09-2025,Andaman and Nicobar Islands,South Andaman,744101,5,5
3,01-09-2025,Andaman and Nicobar Islands,South Andaman,744206,9,4
4,12-09-2025,Andaman and Nicobar Islands,South Andaman,744105,9,5
...,...,...,...,...,...,...
1861103,29-12-2025,West Bengal,Uttar Dinajpur,733201,4,9
1861104,29-12-2025,West Bengal,Uttar Dinajpur,733213,0,1
1861105,29-12-2025,West Bengal,West Midnapore,721304,0,3
1861106,29-12-2025,West Bengal,West Midnapore,721451,2,0
1861107,29-12-2025,West Bengal,West Midnapore,721457,0,1

In [932]:
# Mapping table exported from Excel
mapping = pd.read_excel("District_Mapping.xlsx")  # Make sure table has From_District & To_District columns

# Lowercase and strip spaces for safe matching
mapping['From_District'] = mapping['From_District'].str.lower().str.strip()
mapping['To_District'] = mapping['To_District'].str.lower().str.strip()

In [933]:
df['District_clean'] = df['district'].str.lower().str.strip()

In [934]:
# Convert mapping table to dict
district_dict = dict(zip(mapping['From_District'], mapping['To_District']))

In [935]:
# Replace using mapping
df['Final_District'] = df['District_clean'].map(district_dict)

# If no match, keep original
df['Final_District'] = df['Final_District'].fillna(df['district'])

In [936]:
df['Final_District'] = df['Final_District'].str.title()

In [937]:
df.head()

,date,state,district,pincode,bio_age_5_17,bio_age_17_,District_clean,Final_District
0,01-09-2025,Andaman and Nicobar Islands,Andamans,744103,2,6,andamans,Andamans
1,01-09-2025,Andaman and Nicobar Islands,North And Middle Andaman,744205,6,4,north and middle andaman,North And Middle Andaman
2,01-09-2025,Andaman and Nicobar Islands,South Andaman,744101,5,5,south andaman,South Andaman
3,01-09-2025,Andaman and Nicobar Islands,South Andaman,744206,9,4,south andaman,South Andaman
4,12-09-2025,Andaman and Nicobar Islands,South Andaman,744105,9,5,south andaman,South Andaman

In [938]:
df['Final_District'] = df['Final_District'].str.replace('*', '', regex=False)

In [939]:
df_sorted = df.sort_values(by='Final_District').reset_index(drop=True)

In [940]:
display(df_sorted['Final_District'].unique())

array(['?', 'Adilabad', 'Agarmalwa', 'Agra', 'Ahilyanagar', 'Ahmedabad',
       'Ahmednagar', 'Aizawl', 'Ajmer', 'Akera', 'Akola', 'Alappuzha',
       'Aligarh', 'Alipurduar', 'Alirajpur', 'Alluri Sitharama Raju',
       'Almora', 'Alwar', 'Ambala', 'Ambedkar Nagar', 'Amethi',
       'Amravati', 'Amreli', 'Amritsar', 'Amroha', 'Anakapalli', 'Anand',
       'Anantapur', 'Ananthapuramu', 'Anantnag', 'Anantpur', 'Andamans',
       'Anjaw', 'Annamayya', 'Anugul', 'Anuppur', 'Araria', 'Ariyalur',
       'Arvalli', 'Arwal', 'Ashoknagar', 'Auraiya', 'Aurangabad',
       'Aurangabad(Bh)', 'Ayodhya', 'Azamgarh', 'Bagalkot', 'Bageshwar',
       'Baghpat', 'Bahraich', 'Bajali', 'Baksa', 'Balaghat', 'Balangir',
       'Baleshwar', 'Baleswar', 'Ballari', 'Ballia', 'Bally Jagachha',
       'Balod', 'Baloda Bazar', 'Balotra', 'Balrampur', 'Banas Kantha',
       'Banaskantha', 'Banda', 'Bandipora', 'Bangalore Rural', 'Banka',
       'Bankura', 'Banswara', 'Bapatla', 'Barabanki', 'Baramulla',
       'Baran', 'Barddhaman', 'Bardez', 'Bardhaman', 'Bareilly',
       'Bargarh', 'Barmer', 'Barnala', 'Barpeta', 'Barwani', 'Bastar',
       'Basti', 'Bathinda', 'Baudh', 'Beawar', 'Beed', 'Begusarai',
       'Belagavi', 'Bemetara', 'Bengaluru', 'Bengaluru Rural',
       'Bengaluru South', 'Betul', 'Bhabua', 'Bhadohi',
       'Bhadradri Kothagudem', 'Bhadrak', 'Bhagalpur', 'Bhandara',
       'Bharatpur', 'Bharuch', 'Bhavnagar', 'Bheed', 'Bhilwara', 'Bhind',
       'Bhiwani', 'Bhojpur', 'Bhopal', 'Bidar', 'Bijapur(Kar)', 'Bijnor',
       'Bikaner', 'Bilaspur', 'Birbhum', 'Bishnupur', 'Biswanath',
       'Bokaro', 'Bokaro ', 'Bongaigaon', 'Botad', 'Boudh', 'Budaun',
       'Budgam', 'Bulandshahar', 'Buldhana', 'Bundi', 'Burhanpur',
       'Buxar', 'Cachar', 'Central Delhi', 'Chamarajanagar',
       'Chamarajanagar ', 'Chamba', 'Chamoli', 'Champawat', 'Champhai',
       'Chamrajanagar', 'Chandauli', 'Chandauli ', 'Chandel',
       'Chandigarh', 'Chandrapur', 'Changlang', 'Charaideo',
       'Charkhi Dadri', 'Chatra', 'Chatrapati Sambhaji Nagar',
       'Chengalpattu', 'Chennai', 'Chhatarpur',
       'Chhatrapati Sambhajinagar', 'Chhindwara', 'Chhotaudepur',
       'Chikkaballapura', 'Chikkamagaluru', 'Chikmagalur', 'Chirang',
       'Chitradurga', 'Chitrakoot', 'Chittaurgarh', 'Chittoor',
       'Chittorgarh', 'Chumukedima', 'Churachandpur', 'Churu',
       'Coimbatore', 'Cooch Behar', 'Cuddalore', 'Cuddapah', 'Cuttack',
       'Dadra & Nagar Haveli', 'Dadra And Nagar Haveli', 'Dahod',
       'Dakshin Bastar Dantewada', 'Dakshin Dinajpur', 'Dakshina Kannada',
       'Daman', 'Damoh', 'Dang', 'Dantewada', 'Darbhanga', 'Darjeeling',
       'Darrang', 'Datia', 'Dausa', 'Davanagere', 'Debagarh', 'Deeg',
       'Deeg\xa0', 'Dehradun', 'Deoghar', 'Deoria', 'Devbhumi Dwarka',
       'Dewas', 'Dhalai', 'Dhalai  ', 'Dhamtari', 'Dhanbad', 'Dhar',
       'Dharashiv', 'Dharmapuri', 'Dharwad', 'Dhaulpur', 'Dhemaji',
       'Dhenkanal', 'Dholpur', 'Dhubri', 'Dhule', 'Dibang Valley',
       'Dibrugarh', 'Didwana-Kuchaman', 'Dima Hasao', 'Dimapur',
       'Dindigul', 'Dindori', 'Diu', 'Doda', 'Domjur',
       'Dr. B. R. Ambedkar Konaseema', 'Dumka', 'Dungarpur', 'Durg',
       'East', 'East Champaran', 'East Delhi', 'East Garo Hills',
       'East Godavari', 'East Jaintia Hills', 'East Kameng',
       'East Khasi Hills', 'East Midnapore', 'East Midnapur',
       'East Nimar', 'East Siang', 'East Sikkim', 'East Singhbhum',
       'Eastern West Khasi Hills', 'Eluru', 'Ernakulam', 'Erode', 'Etah',
       'Etawah', 'Faridabad', 'Faridkot', 'Farrukhabad', 'Fatehabad',
       'Fatehgarh Sahib', 'Fatehpur', 'Fazilka', 'Ferozepur', 'Firozabad',
       'Gadag', 'Gadag ', 'Gadchiroli', 'Gajapati', 'Ganderbal',
       'Gandhinagar', 'Ganganagar', 'Ganjam', 'Garhwa', 'Garhwa ',
       'Garhwal', 'Gariyaband', 'Gaurela-Pendra-Marwahi',
       'Gautam Buddha Nagar', 'Gautam Buddha Nagar ', 'Gaya', 'Ghaziabad',
       'Ghazipur', 'Gir Somnath', 'Giridih', 'Goalpara', 'Godda',
       'Golaghat', 'Gomati', 'Gonda', 'Gondia', 'Gondiya ', 'Gopalganj',
       'Gorakhpur', 'Gulbarga', 'Gumla', 'Guna', 'Guntur', 'Gurdaspur',
       'Gurugram', 'Gwalior', 'Hailakandi', 'Hamirpur', 'Hanumakonda',
       'Hanumangarh', 'Hapur', 'Harda', 'Harda ', 'Hardoi', 'Haridwar',
       'Hassan', 'Hathras', 'Haveri', 'Haveri ', 'Hawrah', 'Hazaribagh',
       'Hingoli', 'Hingoli ', 'Hisar', 'Hnahthial', 'Hojai', 'Hooghly',
       'Hoshangabad', 'Hoshiarpur', 'Howrah', 'Hyderabad', 'Idukki',
       'Imphal East', 'Imphal West', 'Indore', 'Jabalpur',
       'Jagatsinghapur', 'Jagatsinghpur', 'Jagitial', 'Jaintia Hills',
       'Jaipur', 'Jaisalmer', 'Jajapur', 'Jajpur', 'Jalandhar', 'Jalaun',
       'Jalgaon', 'Jalna', 'Jalor', 'Jalore', 'Jalpaiguri', 'Jammu',
       'Jamnagar', 'Jamtara', 'Jamui', 'Jangoan', 'Janjgir - Champa',
       'Janjgir Champa', 'Janjgir-Champa', 'Jashpur', 'Jaunpur',
       'Jayashankar Bhupalpally', 'Jehanabad', 'Jhabua', 'Jhajjar',
       'Jhalawar', 'Jhansi', 'Jhargram', 'Jharsuguda', 'Jhunjhunu',
       'Jhunjhunun', 'Jind', 'Jiribam', 'Jodhpur', 'Jogulamba Gadwal',
       'Jorhat', 'Junagadh', 'K. V. Rangareddy', 'K.V. Rangareddy',
       'K.V.Rangareddy', 'Kabeerdham', 'Kachchh', 'Kaimur (Bhabua)',
       'Kaithal', 'Kakching', 'Kakinada', 'Kalaburagi', 'Kalahandi',
       'Kalimpong', 'Kallakurichi', 'Kamareddy', 'Kamle', 'Kamrup',
       'Kamrup Metro', 'Kancheepuram', 'Kandhamal', 'Kangra', 'Kanker',
       'Kannauj', 'Kanniyakumari', 'Kannur', 'Kanpur Dehat',
       'Kanpur Nagar', 'Kapurthala', 'Karaikal', 'Karauli',
       'Karbi Anglong', 'Kargil', 'Karimganj', 'Karimnagar', 'Karnal',
       'Karur', 'Kasaragod', 'Kasganj', 'Kathua', 'Katihar', 'Katni',
       'Kaushambi', 'Kawardha', 'Kendrapara', 'Kendujhar', 'Khagaria',
       'Khairagarh Chhuikhadan Gandai', 'Khairthal-Tijara', 'Khammam',
       'Khandwa', 'Khargone', 'Khawzawl', 'Kheda', 'Kheri', 'Khorda',
       'Khordha', 'Khordha  ', 'Khowai', 'Khunti', 'Kinnaur', 'Kiphire',
       'Kishanganj', 'Kishtwar', 'Kodagu', 'Koderma', 'Kohima',
       'Kokrajhar', 'Kolar', 'Kolasib', 'Kolhapur', 'Kolkata', 'Kollam',
       'Komaram Bheem', 'Kondagaon', 'Koppal', 'Koraput', 'Korba',
       'Korea', 'Kota', 'Kotputli-Behror', 'Kottayam', 'Kozhikode',
       'Kra Daadi', 'Krishna', 'Krishnagiri', 'Kulgam', 'Kullu',
       'Kupwara', 'Kurnool', 'Kurukshetra', 'Kurung Kumey', 'Kushinagar',
       'Kushinagar ', 'Lahaul And Spiti', 'Lahul And Spiti', 'Lakhimpur',
       'Lakhisarai', 'Lakshadweep', 'Lalitpur', 'Latehar', 'Latur',
       'Lawngtlai', 'Leh', 'Leh (Ladakh)', 'Leparada', 'Lohardaga',
       'Lohit', 'Longding', 'Longleng', 'Lower Dibang Valley',
       'Lower Siang', 'Lower Subansiri', 'Lucknow', 'Ludhiana', 'Lunglei',
       'Madhepura', 'Madhubani', 'Madurai', 'Mahabubabad', 'Maharajganj',
       'Mahasamund', 'Mahbubnagar', 'Mahendragarh', 'Mahesana',
       'Mahisagar', 'Mahoba', 'Mahoba ', 'Mahrajganj', 'Maihar',
       'Mainpuri', 'Majuli', 'Malappuram', 'Malda', 'Malerkotla',
       'Malkangiri', 'Mamit', 'Mammit', 'Mancherial', 'Mandi', 'Mandla',
       'Mandsaur', 'Mandya', 'Manendragarhchirmiribharatpur',
       'Manendragarh–Chirmiri–Bharatpur', 'Mansa', 'Marigaon', 'Mathura',
       'Mau', 'Mauganj', 'Mayiladuthurai', 'Mayurbhanj', 'Medak',
       'Medchal-Malkajgiri', 'Medchal?Malkajgiri', 'Medchal−Malkajgiri',
       'Meerut', 'Meluri', 'Mewat', 'Midnapore', 'Mirzapur', 'Moga',
       'Mohali', 'Mohalla-Manpur-Ambagarh Chowki',
       'Mohla-Manpur-Ambagarh Chouki', 'Mokokchung', 'Mon', 'Moradabad',
       'Morbi', 'Morena', 'Muktsar', 'Mulugu', 'Mumbai', 'Mumbai City',
       'Mumbai Suburban', 'Mumbai( Sub Urban )', 'Mungeli', 'Munger',
       'Murshidabad', 'Muzaffarnagar', 'Muzaffarpur', 'Mysuru', 'N. T. R',
       'Nabarangapur', 'Nadia', 'Nagaon', 'Nagapattinam', 'Nagarkurnool',
       'Nagaur', 'Nagpur', 'Nainital', 'Najafgarh', 'Nalanda', 'Nalbari',
       'Nalgonda', 'Namakkal', 'Namchi', 'Namsai', 'Nanded', 'Nandurbar',
       'Nandurbar ', 'Nandyala', 'Narayanpet', 'Narayanpur', 'Narmada',
       'Narmadapuram', 'Narsimhapur', 'Nashik', 'Navsari', 'Nawada',
       'Nawanshahr', 'Nayagarh', 'Neemuch', 'Nellore', 'New Delhi',
       'Nicobars', 'Nirmal', 'Niuland', 'Niwari', 'Nizamabad', 'Noklak',
       'North', 'North 24 Parganas', 'North And Middle Andaman',
       'North Cachar Hills', 'North Delhi', 'North Dinajpur',
       'North East', 'North East Delhi', 'North Garo Hills', 'North Goa',
       'North Sikkim', 'North Tripura', 'North Twenty Four Parganas',
       'North West Delhi', 'Nuapada', 'Pakke Kessang', 'Pakur',
       'Palakkad', 'Palamu', 'Palghar', 'Pali', 'Palnadu', 'Palwal',
       'Panch Mahals', 'Panchkula', 'Pandhurna', 'Panipat', 'Panna',
       'Papum Pare', 'Parbhani', 'Parvathipuram Manyam',
       'Paschim Bardhaman', 'Paschim Medinipur', 'Pashchim Champaran',
       'Pashchimi Singhbhum', 'Patan', 'Pathanamthitta', 'Pathankot',
       'Patiala', 'Patna', 'Pauri Garhwal', 'Peddapalli', 'Perambalur',
       'Peren', 'Phalodi', 'Phek', 'Pherzawl', 'Pilibhit', 'Pithoragarh',
       'Poonch', 'Porbandar', 'Prakasam', 'Pratapgarh', 'Prayagraj',
       'Puducherry', 'Pudukkottai', 'Pulwama', 'Punch', 'Pune',
       'Purba Bardhaman', 'Purba Medinipur', 'Purbi Champaran',
       'Purbi Singhbhum', 'Puri', 'Purlia', 'Purnia', 'Purulia',
       'Raebareli', 'Raichur', 'Raigad', 'Raigarh', 'Raigarh(Mh)',
       'Raipur', 'Raisen', 'Rajanna Sircilla', 'Rajgarh', 'Rajkot',
       'Rajnandgaon', 'Rajouri', 'Rajsamand', 'Ramanagar',
       'Ramanathapuram', 'Ramban', 'Ramgarh', 'Rampur', 'Ranchi',
       'Rangareddy', 'Ranipet', 'Ratlam', 'Ratnagiri', 'Rayagada',
       'Reasi', 'Rewa', 'Rewari', 'Ri Bhoi', 'Rohtak', 'Rohtas',
       'Rudraprayag', 'Rupnagar', 'S.A.S Nagar(Mohali)', 'Sabar Kantha',
       'Sagar', 'Saharanpur', 'Saharsa', 'Sahebganj', 'Saiha', 'Saitual',
       'Sakti', 'Salem', 'Salumbar', 'Samastipur', 'Samba', 'Sambalpur',
       'Sambhal', 'Sangareddy', 'Sangli', 'Sangrur', 'Sant Kabir Nagar',
       'Sant Ravidas Nagar', 'Sant Ravidas Nagar Bhadohi', 'Saran',
       'Sarangarh-Bilaigarh', 'Sas Nagar (Mohali)', 'Satara', 'Satna',
       'Sawai Madhopur', 'Sehore', 'Senapati', 'Seoni', 'Sepahijala',
       'Seraikela-Kharsawan', 'Serchhip', 'Shahdara', 'Shahdol',
       'Shaheed Bhagat Singh Nagar', 'Shahjahanpur', 'Shajapur',
       'Shamator', 'Shamli', 'Sheikhpura', 'Sheohar', 'Sheopur',
       'Shi-Yomi', 'Shimla', 'Shivamogga', 'Shivpuri', 'Shopian',
       'Shrawasti', 'Siang', 'Siddharthnagar', 'Siddipet', 'Sidhi',
       'Sikar', 'Simdega', 'Sindhudurg', 'Singrauli', 'Sirmaur', 'Sirohi',
       'Sirsa', 'Sitamarhi', 'Sitapur', 'Sivaganga', 'Sivasagar', 'Siwan',
       'Solan', 'Solapur', 'Sonapur', 'Sonbhadra', 'Sonipat', 'Sonitpur',
       'South', 'South 24 Pargana', 'South 24 Parganas', 'South Andaman',
       'South Delhi', 'South Dinajpur', 'South Dumdum(M)',
       'South East Delhi', 'South Garo Hills', 'South Goa',
       'South Salmara Mankachar', 'South Sikkim', 'South Tripura',
       'South Twenty Four Parganas', 'South West Delhi',
       'South West Garo Hills', 'South West Khasi Hills',
       'Sri Muktsar Sahib', 'Sri Potti Sriramulu Nellore',
       'Sri Sathya Sai', 'Sribhumi', 'Srikakulam', 'Srinagar',
       'Subarnapur', 'Sukma', 'Sultanpur', 'Sundargarh', 'Sundergarh',
       'Supaul', 'Surajpur', 'Surat', 'Surendra Nagar', 'Surguja',
       'Suryapet', 'Tamenglong', 'Tamulpur District', 'Tapi',
       'Tarn Taran', 'Tawang', 'Tehri Garhwal', 'Tenkasi', 'Thane',
       'Thanjavur', 'The Nilgiris', 'Theni', 'Thiruvallur',
       'Thiruvananthapuram', 'Thiruvarur', 'Thoothukkudi', 'Thoubal',
       'Thrissur', 'Tikamgarh', 'Tinsukia', 'Tirap', 'Tiruchirappalli',
       'Tirunelveli', 'Tirupathur', 'Tirupati', 'Tirupattur', 'Tiruppur',
       'Tiruvannamalai', 'Tiruvarur', 'Tiswadi', 'Tonk', 'Tseminyu',
       'Tuensang', 'Tumakuru', 'Udaipur', 'Udalguri', 'Udham Singh Nagar',
       'Udhampur', 'Udupi', 'Udupi ', 'Ujjain', 'Ukhrul', 'Umaria', 'Una',
       'Unakoti', 'Unnao', 'Upper Siang', 'Upper Subansiri',
       'Uttar Bastar Kanker', 'Uttar Dinajpur', 'Uttara Kannada',
       'Uttarkashi', 'Vadodara', 'Vaishali', 'Valsad', 'Varanasi',
       'Vellore', 'Vidisha', 'Vijayanagara', 'Vijayapura', 'Vikarabad',
       'Villupuram', 'Viluppuram', 'Virudhunagar', 'Visakhapatnam',
       'Vizianagaram', 'Wanaparthy', 'Warangal', 'Warangal (Rural)',
       'Warangal (Urban)', 'Wardha', 'Washim', 'Washim ', 'Wayanad',
       'West', 'West Champaran', 'West Delhi', 'West Garo Hills',
       'West Godavari', 'West Jaintia Hills', 'West Kameng',
       'West Karbi Anglong', 'West Khasi Hills', 'West Medinipur',
       'West Midnapore', 'West Nimar', 'West Siang', 'West Sikkim',
       'West Singhbhum', 'West Tripura', 'Wokha', 'Y. S. R', 'Yadadri.',
       'Yadgir', 'Yamuna Nagar', 'Yanam', 'Yavatmal', 'Zunheboto'],
      dtype=object)

In [941]:
df_sorted['Final_District'].unique().size

882

In [942]:
df_sorted['state'].unique()

array(['Jammu and Kashmir', 'Telangana', 'Andhra Pradesh',
       'Madhya Pradesh', 'Uttar Pradesh', 'Maharashtra', 'Gujarat',
       'Mizoram', 'Rajasthan', 'Haryana', 'Kerala', 'West Bengal',
       'Uttarakhand', 'Punjab', 'Jammu & Kashmir',
       'Andaman & Nicobar Islands', 'Andaman and Nicobar Islands',
       'Arunachal Pradesh', 'Odisha', 'Orissa', 'Bihar', 'Tamil Nadu',
       'Karnataka', 'Assam', 'Chhattisgarh', 'Goa', 'Himachal Pradesh',
       'Manipur', 'Jharkhand', 'Delhi', 'Chandigarh', 'Tamilnadu',
       'andhra pradesh', 'Nagaland', 'Pondicherry',
       'Dadra and Nagar Haveli and Daman and Diu', 'Dadra & Nagar Haveli',
       'Dadra and Nagar Haveli', 'Daman & Diu', 'Daman and Diu',
       'Tripura', 'Sikkim', 'Meghalaya', 'odisha', 'Uttaranchal',
       'West  Bengal', 'West bengal', 'West Bangal', 'Westbengal',
       'WEST BENGAL', 'WESTBENGAL', 'Puducherry', 'Ladakh', 'Lakshadweep',
       'ODISHA', 'Chhatisgarh'], dtype=object)

In [943]:
df_sorted['state'] = df_sorted['state'].str.replace('&', 'and', regex=False)

In [944]:
df_sorted['state'] = df_sorted['state'].str.replace('Orissa', 'Odisha', regex=False)

In [945]:
df_sorted['state'] = df_sorted['state'].str.replace('Chhatisgarh', 'Chhattisgarh', regex=False)

In [946]:
df_sorted['state'] = df_sorted['state'].str.replace('odisha', 'Odisha', regex=False)

In [947]:
df_sorted['state'] = df_sorted['state'].str.replace('ODISHA', 'Odisha', regex=False)

In [948]:
df_sorted['state'] = df_sorted['state'].str.replace('andhra pradesh', 'Andhra Pradesh', regex=False)

In [949]:
df_sorted['state'] = df_sorted['state'].str.replace('andhra pradesh', 'Andhra Pradesh', regex=False)

In [950]:
df_sorted['state'] = df_sorted['state'].str.replace('West bengal', 'West Bengal', regex=False)

In [951]:
df_sorted['state'] = df_sorted['state'].str.replace('West  Bengal', 'West Bengal', regex=False)

In [952]:
df_sorted['state'] = df_sorted['state'].str.replace('West Bangal', 'West Bengal', regex=False)

In [953]:
df_sorted['state'] = df_sorted['state'].str.replace('Westbengal', 'West Bengal', regex=False)

In [954]:
df_sorted['state'] = df_sorted['state'].str.replace('WEST BENGAL', 'West Bengal', regex=False)

In [955]:
df_sorted['state'] = df_sorted['state'].str.replace('WESTBENGAL', 'West Bengal', regex=False)

In [956]:
df_sorted['state'] = df_sorted['state'].str.replace('Dadra and Nagar Haveli and Daman and Diu', 'Daman and Diu', regex=False)

In [957]:
df_sorted['state'] = df_sorted['state'].str.replace('Dadra and Nagar Haveli', 'Daman and Diu', regex=False)

In [958]:
df_sorted['state'] = df_sorted['state'].str.replace('Daman and Diu','Dadra and Nagar Haveli and Daman and Diu', regex=False)

In [959]:
df_sorted['state'] = df_sorted['state'].str.replace('Uttaranchal', 'Uttarakhand', regex=False)

In [960]:
df_sorted['state'] = df_sorted['state'].str.replace('Pondicherry', 'Puducherry', regex=False)

In [961]:
df_sorted['state'] = df_sorted['state'].str.replace('Tamilnadu', 'Tamil Nadu', regex=False)

In [962]:
# df_sorted.loc[(df_sorted['state']=='Sikkim') & (df_sorted['Final_District']=='West')]['Final_District'] = 'West Sikkim'

In [963]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Ahmednagar', 'Ahilyanagar', regex=False)

In [964]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Anantapur', 'Ananthapuramu', regex=False)

In [965]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Anantpur', 'Ananthapuramu', regex=False)

In [966]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Aurangabad(Bh)', 'Aurangabad', regex=False)

In [967]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Baleswar', 'Baleshwar', regex=False)

In [968]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Banas Kantha', 'Banaskantha', regex=False)

In [969]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Bangalore', 'Bengaluru', regex=False)

In [970]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Bheed', 'Beed', regex=False)

In [971]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Bokaro ', 'Bokaro', regex=False)

In [972]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Chamarajanagar ', 'Chamrajanagar', regex=False)

In [973]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Chamarajanagar', 'Chamrajanagar', regex=False)

In [974]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Chandauli ', 'Chandauli', regex=False)

In [975]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Chatrapati Sambhaji Nagar ', 'Chhatrapati Sambhajinagar', regex=False)

In [976]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Chatrapati Sambhaji Nagar ', 'Chhatrapati Sambhajinagar', regex=False)

In [977]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Bardhaman', 'Barddhaman', regex=False)

In [978]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Chikmagalur', 'Chikkamagaluru', regex=False)

In [979]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Chittaurgarh', 'Chittorgarh', regex=False)

In [980]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Dadra & Nagar Haveli', 'Dadra and Nagar Haveli', regex=False)

In [981]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Deeg\xa0', 'Deeg', regex=False)

In [982]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Dhalai  ', 'Dhalai', regex=False)

In [983]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Dhaulpur  ', 'Dholpur', regex=False)

In [984]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('East Midnapur', 'East Midnapore', regex=False)

In [985]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Gadag ', 'Gadag', regex=False)

In [986]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Garhwa ', 'Garhwa', regex=False)

In [987]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Gautam Buddha Nagar ', 'Gautam Buddha Nagar', regex=False)

In [988]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Gondiya', 'Gondia', regex=False)

In [989]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Harda ', 'Harda', regex=False)

In [990]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Hawrah', 'Howrah', regex=False)

In [991]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Hingoli ', 'Hingoli', regex=False)

In [992]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Jajpur', 'Jajapur', regex=False)

In [993]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Jalor', 'Jalore', regex=False)

In [994]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Janjgir - Champa', 'Janjgir-Champa', regex=False)

In [995]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Janjgir Champa', 'Janjgir-Champa', regex=False)

In [996]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Jhunjhunun', 'Jhunjhunu', regex=False)

In [997]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('K. V. Rangareddy', 'K.V. Rangareddy', regex=False)

In [998]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('K.V.Rangareddy', 'K.V. Rangareddy', regex=False)

In [999]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Khorda', 'Khordha', regex=False)

In [1000]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Khordha  ', 'Khordha', regex=False)

In [1001]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Kushinagar ', 'Kushinagar', regex=False)

In [1002]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Lahul And Spiti', 'Lahaul And Spiti', regex=False)

In [1003]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Leh (Ladakh)', 'Leh', regex=False)

In [1004]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Mammit', 'Mamit', regex=False)

In [1005]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Manendragarhchirmiribharatpur', 'Manendragarh–Chirmiri–Bharatpur', regex=False)

In [1006]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Medchal?Malkajgiri', 'Medchal-Malkajgiri', regex=False)

In [1007]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Medchal−Malkajgiri', 'Medchal-Malkajgiri', regex=False)

In [1008]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Mohalla-Manpur-Ambagarh Chowki', 'Mohla-Manpur-Ambagarh Chouki', regex=False)

In [1009]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Muktsar', 'Sri Mukstar Sahib', regex=False)

In [1010]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Nandurbar ', 'Nandurbar', regex=False)

In [1011]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('North Twenty Four Parganas', 'North 24 Parganas', regex=False)

In [1012]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Paschim Medinipur', 'Paschim Midnapore', regex=False)

In [1013]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Purba Medinipur', 'Purba Midnapore', regex=False)

In [1014]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Rangareddy', 'K. V. Rangareddy', regex=False)

In [1015]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Saiha', 'Siaha', regex=False)

In [1016]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Sant Ravidas Nagar', 'Bhadohi', regex=False)

In [1017]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Sant Ravidas Nagar Bhadohi', 'Bhadohi', regex=False)

In [1018]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Sas Nagar', 'S.A.S. Nagar', regex=False)

In [1019]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Sonapur', 'Sonepur', regex=False)

In [1020]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('South 24 Pargana', 'South 24 Parganas', regex=False)

In [1021]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Subarnapur', 'Sonepur', regex=False)

In [1022]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Sundergarh', 'Sundargarh', regex=False)

In [1023]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Udupi ', 'Udupi', regex=False)

In [1024]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Villupuram ', 'Viluppuram', regex=False)

In [1025]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Washim ', 'Washim', regex=False)

In [1026]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('West Medinipur', 'West Midnapore', regex=False)

In [1027]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Washim ', 'Washim', regex=False)

In [1028]:
df_sorted['Final_District'].unique().size

834

In [1029]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('South 24 Parganass', 'South 24 Parganas', regex=False)

In [1030]:
districts_map = {
    'North': 'North Sikkim',
    'South': 'South Sikkim',
    'East': 'East Sikkim',
    'West': 'West Sikkim'
}

for old_district, new_district in districts_map.items():
    df_sorted.loc[
        (df_sorted['state'] == 'Sikkim') & (df_sorted['Final_District'] == old_district),
        'Final_District'
    ] = new_district

In [1031]:
print("Unique districts in Sikkim after replacement:")
display(df_sorted[df_sorted['state'] == 'Sikkim']['Final_District'].unique())

Unique districts in Sikkim after replacement:

array(['East Sikkim', 'Namchi', 'North Sikkim', 'South Sikkim',
       'West Sikkim'], dtype=object)

In [1032]:
districts_map = {
    'North East': 'North East Delhi'
}

for old_district, new_district in districts_map.items():
    df_sorted.loc[
        (df_sorted['state'] == 'Delhi') & (df_sorted['Final_District'] == old_district),
        'Final_District'
    ] = new_district

In [1033]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Baudh', 'Boudh', regex=False)

In [1034]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Chatrapati Sambhaji Nagar', 'Chhatrapati Sambhajinagar', regex=False)

In [1035]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Dadra And Nagar Haveli', 'Dadra and Nagar Haveli', regex=False)

In [1036]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Dakshin Bastar Dantewada', 'Dantewada', regex=False)

In [1037]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Debagarh', 'Deogarh', regex=False)

In [1038]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Dhaulpur', 'Dholpur', regex=False)

In [1039]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Gondia ', 'Gondia', regex=False)

In [1040]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Haveri ', 'Haveri', regex=False)

In [1041]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Jaloree', 'Jalore', regex=False)

In [1042]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Jagatsinghpur', 'Jagatsinghapur', regex=False)

In [1043]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('K.V. K. V. Rangareddy', 'K.V. Rangareddy', regex=False)

In [1044]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Karimganj', 'Sribhumi', regex=False)

In [1045]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Mahoba ', 'Mahoba', regex=False)

In [1046]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Mumbai( Sub Urban )', 'Mumbai Suburban', regex=False)

In [1047]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Punch', 'Poonch', regex=False)

In [1048]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Purlia', 'Purulia', regex=False)

In [1049]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Bhadohi Bhadohi', 'Bhadohi', regex=False)

In [1050]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('South Twenty Four Parganas', 'South 24 Parganas', regex=False)

In [1051]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Sri Sri Mukstar Sahib Sahib', 'Sri Mukstar Sahib', regex=False)

In [1052]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Villupuram', 'Viluppuram', regex=False)

In [1053]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Khandwa', 'East Nimar', regex=False)

In [1054]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Khargone', 'West Nimar', regex=False)

In [1055]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('Raigarh(Mh)', 'Raigad', regex=False)

In [1056]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('?', 'Unknown', regex=False)

In [1057]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('S.A.S Nagar(Mohali)', 'S.A.S. Nagar (Mohali)', regex=False)

In [1058]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('K. V. Rangareddy', 'K.V. Rangareddy', regex=False)

In [1059]:
df_sorted['Final_District'] = df_sorted['Final_District'].str.replace('', '', regex=False)

In [1060]:
df_sorted['Final_District'].unique().size

805

In [1061]:
df_sorted = df_sorted.drop(columns=['district', 'District_clean'])
display(df_sorted.head())

,date,state,pincode,bio_age_5_17,bio_age_17_,Final_District
0,17-11-2025,Jammu and Kashmir,181206,0,1,Unknown
1,14-12-2025,Telangana,504310,1,0,Adilabad
2,14-12-2025,Telangana,504309,3,2,Adilabad
3,14-12-2025,Telangana,504299,1,0,Adilabad
4,14-12-2025,Telangana,504295,0,1,Adilabad

In [1062]:
df_sorted = df_sorted.rename(columns={'Final_District': 'District'})
display(df_sorted.head())

         date              state  pincode  bio_age_5_17  bio_age_17_  District
0  17-11-2025  Jammu and Kashmir   181206             0            1   Unknown
1  14-12-2025          Telangana   504310             1            0  Adilabad
2  14-12-2025          Telangana   504309             3            2  Adilabad
3  14-12-2025          Telangana   504299             1            0  Adilabad
4  14-12-2025          Telangana   504295             0            1  Adilabad

#### Adding Columns

In [1063]:
df_sorted['total_updates'] = df_sorted['bio_age_5_17'] + df_sorted['bio_age_17_']
# display(df_sorted.head())

In [1064]:
df_sorted['child_ratio'] = df_sorted.apply(lambda row: round(row['bio_age_5_17'] / row['total_updates'], 4) if row['total_updates'] != 0 else 0.0, axis=1)

In [1065]:
df_sorted['adult_ratio'] = df_sorted.apply(lambda row: round(row['bio_age_17_'] / row['total_updates'], 4) if row['total_updates'] != 0 else 0.0, axis=1)
display(df_sorted.head())

,date,state,pincode,bio_age_5_17,bio_age_17_,District,total_updates,child_ratio,adult_ratio
0,17-11-2025,Jammu and Kashmir,181206,0,1,Unknown,1,0.0,1.0
1,14-12-2025,Telangana,504310,1,0,Adilabad,1,1.0,0.0
2,14-12-2025,Telangana,504309,3,2,Adilabad,5,0.6,0.4
3,14-12-2025,Telangana,504299,1,0,Adilabad,1,1.0,0.0
4,14-12-2025,Telangana,504295,0,1,Adilabad,1,0.0,1.0

In [1066]:
df_sorted['state'].unique()

array(['Jammu and Kashmir', 'Telangana', 'Andhra Pradesh',
       'Madhya Pradesh', 'Uttar Pradesh', 'Maharashtra', 'Gujarat',
       'Mizoram', 'Rajasthan', 'Haryana', 'Kerala', 'West Bengal',
       'Uttarakhand', 'Punjab', 'Andaman and Nicobar Islands',
       'Arunachal Pradesh', 'Odisha', 'Bihar', 'Tamil Nadu', 'Karnataka',
       'Assam', 'Chhattisgarh', 'Goa', 'Himachal Pradesh', 'Manipur',
       'Jharkhand', 'Delhi', 'Chandigarh', 'Nagaland', 'Puducherry',
       'Dadra and Nagar Haveli and Daman and Diu', 'Tripura', 'Sikkim',
       'Meghalaya', 'Ladakh', 'Lakshadweep'], dtype=object)

In [1071]:
df_sorted.columns

Index(['date', 'state', 'pincode', 'bio_age_5_17', 'bio_age_17_', 'District',
       'total_updates', 'child_ratio', 'adult_ratio'],
      dtype='object')

In [1072]:
df_sorted = df_sorted.rename(columns={'state': 'State','date':'Date of Updation','pincode':'Pincode',
                                      'bio_age_5_17':'Bio_age_5_17','bio_age_17':'Bio_age_17_',
                                      'total_updates':'Total_Updates','child_ratio':'Child_Ratio',
                                      'adult_ratio':'Adult_Ratio'})

In [1073]:
df_sorted.to_csv('UIDAI_Bio_Cleaned_Data.csv', index=False)

## Analysis

In [1075]:
import matplotlib.pyplot as plt
import seaborn as sns
import numpy as np

plt.rcParams["figure.figsize"] = (10,5)
sns.set_style("whitegrid")

In [1098]:
data=pd.read_csv('UIDAI_Bio_Cleaned_Data.csv')

In [1099]:
data.shape

(1861108, 9)

In [1100]:
data.columns

Index(['Date of Updation', 'State', 'Pincode', 'Bio_age_5_17', 'bio_age_17_',
       'District', 'Total_Updates', 'Child_Ratio', 'Adult_Ratio'],
      dtype='object')

In [1101]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1861108 entries, 0 to 1861107
Data columns (total 9 columns):
 #   Column            Dtype
---  ------            -----
 0   Date of Updation  object
 1   State             object
 2   Pincode           int64
 3   Bio_age_5_17      int64
 4   bio_age_17_       int64
 5   District          object
 6   Total_Updates     int64
 7   Child_Ratio       float64
 8   Adult_Ratio       float64
dtypes: float64(2), int64(4), object(3)
memory usage: 127.8+ MB

In [1102]:
selected_columns = ['Bio_age_5_17', 'bio_age_17_', 'Total_Updates', 'Child_Ratio', 'Adult_Ratio']
display(data[selected_columns].describe())

       Bio_age_5_17   bio_age_17_  Total_Updates   Child_Ratio   Adult_Ratio
count  1.861108e+06  1.861108e+06   1.861108e+06  1.861108e+06  1.861108e+06
mean   1.839058e+01  1.909413e+01   3.748471e+01  4.728444e-01  5.271492e-01
std    8.370421e+01  8.806502e+01   1.623302e+02  3.038688e-01  3.038694e-01
min    0.000000e+00  0.000000e+00   0.000000e+00  0.000000e+00  0.000000e+00
25%    1.000000e+00  1.000000e+00   3.000000e+00  2.500000e-01  3.333000e-01
50%    3.000000e+00  4.000000e+00   8.000000e+00  5.000000e-01  5.000000e-01
75%    1.100000e+01  1.000000e+01   2.200000e+01  6.667000e-01  7.500000e-01
max    8.002000e+03  7.625000e+03   1.338100e+04  1.000000e+00  1.000000e+00

In [1103]:
data.isna().sum()

Date of Updation    0
State               0
Pincode             0
Bio_age_5_17        0
bio_age_17_         0
District            0
Total_Updates       0
Child_Ratio         0
Adult_Ratio         0
dtype: int64

### Feature Engineering

In [1104]:
data["Date of Updation"] = pd.to_datetime(data["Date of Updation"], dayfirst=True)

In [1105]:
data["Year"] = data["Date of Updation"].dt.year
data["Month"] = data["Date of Updation"].dt.month
data["Month_Year"] = data["Date of Updation"].dt.to_period("M")

In [1106]:
data.head()

,Date of Updation,State,Pincode,Bio_age_5_17,bio_age_17_,District,Total_Updates,Child_Ratio,Adult_Ratio,Year,Month,Month_Year
0,2025-11-17,Jammu and Kashmir,181206,0,1,Unknown,1,0.0,1.0,2025,11,2025-11
1,2025-12-14,Telangana,504310,1,0,Adilabad,1,1.0,0.0,2025,12,2025-12
2,2025-12-14,Telangana,504309,3,2,Adilabad,5,0.6,0.4,2025,12,2025-12
3,2025-12-14,Telangana,504299,1,0,Adilabad,1,1.0,0.0,2025,12,2025-12
4,2025-12-14,Telangana,504295,0,1,Adilabad,1,0.0,1.0,2025,12,2025-12